[build-system]
requires = [
    "setuptools>=59",
    "wheel",
    "pyvex==9.2.0.dev0; platform_machine == 'x86_64' or platform_machine == 'AMD64'",
    "unicorn==1.0.2rc4; platform_machine == 'x86_64' or platform_machine == 'AMD64'",
]
build-backend = "setuptools.build_meta"
